linters:
  enable-all: true
  disable:
    - gci
    - gofmt
    - scopelint
    - interfacer
    - golint
    - maligned
    - exhaustivestruct
    - gofumpt
linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
  gomnd:
    settings:
      mnd:
        ignored-files: config.go
  gofumpt:
    lang-version: "1.17"
    extra-rules: true
  forbidigo:
    forbid:
      - ^(fmt\.Print.*|print|println)$
      - ^panic$

issues:
  exclude-rules:
    - path: internal/store/
      linters:
        - dupl
    - path: _test\.go
      linters:
        - funlen
        - goconst
    - path: test/integration
      linters:
        - paralleltest
    - path: test
      linters:
        - wrapcheck
