version: '3.8'
services:
  db:
    image: postgres
  db-migrate:
    image: migrate/migrate
    volumes:
      - ./internal/db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable", "up"]
  go:
    image: golang:1.16-alpine
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
