FROM postgres:13.2
COPY ./dbinit.sh /app
ENTRYPOINT ["sh", "-c", "/app/dbinit.sh"]

FROM migrate/migrate
COPY ./internal/db/migrations /app
ENTRYPOINT ["sh", "-c"]
CMD ["migrate -path /app -database postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE} up"]
