version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202104-01
    working_directory: ~/data
    steps:
      - checkout
      - run: make db-start
      - run: make db-init
      - run: make db-migrate
      - run: make test
workflows:
  test:
    jobs:
      - test
