openapi: "3.0.0"
info:
  description: "
    Welcome to the Ogee API.
    \n
    \n
    <b>Authentication</b>
    \n
    \n
    The API must authenticate using HTTP headers. Pass your api key in the <code>X-OGEE-API-KEY</code> header and your api secret in the <code>X-OGEE-API-SECRET</code> header.
    \n
    \n
    Example:
    \n
    \n
    <code>
    X-OGEE-API-KEY: yourkey
    </code>
    \n
    \n
    <code>
    X-OGEE-API-SECRET: yoursecret
    </code>
  "
  version: 1.0.0
  title: "Ogee API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "support@ogee.dev"
servers:
  - url: https://api.ogee.dev/api
components:
  securitySchemes:
    key:
      type: apiKey
      in: header
      name: X-OGEE-API-KEY
    secret:
      type: apiKey
      in: header
      name: X-OGEE-API-SECRET
security:
  - key: []
    secret: []
tags:
  - name: "profiles"
    description: "Information for government benefits for the user"
paths:
  $ref: profiles.yaml
