swagger: "2.0"
info:
  description: "Welcome to the Ogee API."
  version: "1.0.0"
  title: "Ogee API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "support@ogee.dev"
host: "api.ogee.dev"
basePath: "/api/v1"
tags:
- name: "profiles"
  description: "Information for government benefits for the user"
schemes:
- "https"
paths:
  $ref: profiles.yaml
