/profiles:
  post:
    tags:
    - "profiles"
    summary: "Profiles"
    operationId: "createProfile"
    consumes:
    - "application/json"
    produces:
    - "application/json"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/definitions/ProfilesRequest"
    responses:
      "201":
        description: "Success"
        content:
          application/json:
            schema:
              $ref: "#/definitions/ProfilesResponse"
/profiles/{profile_id}:
  get:
    tags:
    - "profiles"
    summary: "Profiles"
    operationId: "getProfile"
    produces:
    - "application/json"
    parameters:
    - in: "path"
      name: "profile_id"
      description: "Id of the profile to be returned"
      required: true
    responses:
      "200":
        description: "Success"
        content:
          application/json:
            schema:
              $ref: "#/definitions/ProfilesResponse"
definitions:
  ProfilesRequest:
    type: "object"
    properties:
      username:
        type: "string"
        format: "email"
      password:
        type: "string"
        format: "password"
  ProfilesResponse:
    type: "object"
    properties:
      profile_id:
        type: "string"
        format: "uuid"
      ebt_snap_balance:
        type: "number"
        format: "float"
