name: pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_DROP: yes
      DB_HOST: postgres
      DB_NAME: go_server_test
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_SSL: false
      DB_SSL_MODE: disable
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: make lint-docker
      - run: make db-start
      - run: make db-init
      - run: make db-migrate
      - run: make test-docker
  deploy:
    name: deploy to aws
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::408204130528:role/SunburstDevAdmin
        aws-region: us-east-2
